const project = [
    {
        id: 1,
        projectImage:"connect4.png",
        title: 'Connect 4 Game',
        techStack: 'React, CSS',
        siteLink: "https://spyde-connect-4.netlify.app",
        githubLink: "https://github.com/Karthikeyan1411/Connect-4",
    },
    {
        id: 2,
        projectImage:"color_changer.png",
        title: 'Color Changer',
        techStack: 'React, CSS',
        siteLink: "https://spyde-color-changer.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Color-Changer",
    },
    {
        id: 3,
        projectImage:"e_commerce_online_shop.png",
        title: 'E-Commerce Online Shop',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-e-commerce.netlify.app",
        githubLink: "https://github.com/Karthikeyan1411/Internpe/tree/main/Task_2_E_Commerce_Website",
    },
    {
        id: 4,
        projectImage:"social_media_app.png",
        title: 'Social Media App',
        techStack: 'React, CSS',
        siteLink: "https://spyde-social-app.netlify.app",
        githubLink: "https://github.com/Karthikeyan1411/React_Social_Media_App",
    },
    {
        id: 5,
        projectImage:"todo_app.png",
        title: 'Todo App',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-todo-list-app.netlify.app",
        githubLink: "https://github.com/Karthikeyan1411/Internpe/tree/main/Task_3_ToDo_App",
    },
    {
        id: 6, 
        projectImage:"airbnb.png",
        title: 'Airbnb',
        techStack: 'React, CSS',
        siteLink: "https://spyde-bnbair-app.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Airbnb",
    }, 
    {
        id: 7,
        projectImage: "calculator.png",
        title: 'Calculator',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-calc.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Calculator/html"
    },
    {
        id: 8,
        projectImage: "e_commerce_store_using_react.png",
        title: 'E-Commerce Store using React',
        techStack: 'React, CSS',
        siteLink: "https://spyde-e-commerce-store.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/React%20Projects/E-Commerce%20Website/my-app",
    },
    {
        id: 9,
        projectImage:"form_validation.png",
        title: 'Simple Form Validation',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-form-validation.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Form%20Validation%20Page",
    },
    {
        id: 10,
        projectImage:"image_gallery.png",
        title: 'Image Gallery',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-image-gallery.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Image%20Gallery",
    },
    {
        id: 11,
        projectImage:"login_page.png",
        title: 'Login Page',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-form-page.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Form",
    },
    {
        id: 12,
        projectImage:"netflix_clone.png",
        title: 'Netflix Clone',
        techStack: 'HTML, CSS',
        siteLink: "https://spyde-nflix-dupli.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Netflix-Clone",
    },
    {
        id: 13,
        projectImage:"sign_up_page_using_react.png",
        title: 'Sign Up Page using React',
        techStack: 'React, HTML, CSS',
        siteLink: "https://spyde-sign-up-page.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/React%20Projects/SignUp%20Page/my-app",
    },
    {
        id: 14,
        projectImage:"simple_blog.png",
        title: 'Simple Blog',
        techStack: 'HTML, CSS',
        siteLink: "https://spyde-blog.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Blog",
    },
    {
        id: 15,
        projectImage:"simple_counter.png",
        title: 'Simple Counter',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-counter.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/DOM_Counter",
    },
    {
        id: 16,
        projectImage:"simple_landing_page.png",
        title: 'Simple Landing Page',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-landing-page.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Landing%20Page",
    },
    {
        id: 17,
        projectImage:"simple_todo_app.png",
        title: 'Simple Todo App',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-todo-app.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Todo%20App",
    },
    {
        id: 18,
        projectImage:"simple_todo_app_using_react.png",
        title: 'Simple Todo App using React',
        techStack: 'React, CSS',
        siteLink: "https://spyde-todo-app-react.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/React%20Projects/Todo%20App/my-app",
    },
    {
        id: 19,
        projectImage:"student_attendance_qr_code_generator_using_react.png",
        title: 'Student Attendance QR Code Generator using React',
        techStack: 'React, CSS',
        siteLink: "https://spyde-student-attendance-qr.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/React%20Projects/QR%20Code%20Generator",
    },
    {
        id: 20,
        projectImage:"text_to_speech_converter.png",
        title: 'Text to Speech Converter',
        techStack: 'HTML, CSS, JavaScript',
        siteLink: "https://spyde-text-to-speech-converter.netlify.app/",
        githubLink: "https://github.com/Karthikeyan1411/Development-Projects/tree/main/Text%20to%20Speech%20Converter",
    }, 
]

export default project;